### ISSUE TITLE
base_user_role is not in weblate

### ISSUE THREAD

**Issue by hhgabelgaard** [OCA/server-backend#12]
Probably due to missing .pot file. They were deleted by @sbidoul in 19ba7cf. I assume the purpose was to have the new makepot system generate a new .pot file

How can I trigger this .pot file generation?

Only 3 out of 6 addons in this repo has .pot files and are present in weblate

**Comment by pedrobaeza** [comment]
Problem is that .travis.yml is not correctly defined. Fixed in https://github.com/OCA/server-backend/commit/4bb594bffa6248d6ff47b72f3473d0519e51e0c4
