### ISSUE TITLE
[11.0] base_dav incompatible with Radicale 3.0.0 and up

### ISSUE THREAD

**Issue by chrisb-c01** [OCA/server-backend#133]
It seems the Python package Radicale which is used by `base_dav` version 3.0.0 introduces breaking changes making it incompatible with the `base_dav`. Would be good to indicate this/pin Radicale version or make `base_dav` compatible with version 3.0.0. Also see Radicale changelog here: https://github.com/Kozea/Radicale/blob/3.0.0/NEWS.md

Errors I was getting:

```
  File "/../server-backend/base_dav/radicale/auth.py", line 12, in <module>
    class Auth(BaseAuth):
TypeError: NoneType takes no arguments
```

and

```
File "/../server-backend/base_dav/radicale/collection.py", line 26, in <module>
    class FileItem(Item):
TypeError: NoneType takes no arguments
```

**Comment by antoine45170** [comment]
Hello Chris, 
I'm facing the same issue with Radicale 2.1.12. When I tried to launch Odoo server i can the type error for the "class Auth(BaseAuth)". How did you solve the problem ? 
Thank you in advance

**Comment by chrisb-c01** [comment]
@antoine45170 we have pinned radicale to version 2.1.12 in the requirements.txt
