### ISSUE TITLE
[RFC][WIP] Mixin for declarative partitioning of tables (list and range type partitioning)

### ISSUE THREAD

**Issue by daramousk** [OCA/server-backend#16]
Hello,

With postgresql 11.0 out and partitioning support enhanced, we came up with the idea of creating a mixin that when inherited from will help programmers partition their models.

Here are the abstract initial requirements:
Give the user the possibility to partition their tables as shown in https://www.postgresql.org/docs/current/static/ddl-partitioning.html 5.10.2.

Abstract implementation:

1) The models that want to make use of the partition need to inherit from `base_table_partition_mixin` _and_ on the fields that will be used for partitioning need to use `partition_by_range=$range or $list or callable that returns them` 

2) When the module is installed updated the following will take place (or not if they have already been done)

    a) since we cannot partition an already existing table, create create an identical one with the same schema. (in order to not have conflicts with global constrains the table will be created in a new temporary database schema)

    b) based on the $range or $list and the already existing data, create as many partitions as necessary (create the index on this column as well)

    c) find all the foreign key constrains that point to my initial non partitioned table and change them to point to tableB which is partitioned.

    d) drop tableA, move tableB from temporary database schema to public database schema, drop temprory database schema.

3) When it comes to maintenance we do not need to do something.

4) Possibly revert the process when the module is uninstalled?

Pitfalls:
On versions < 10.0 on models.py the relkind is being used and restricted to 'r', 'v' table types while the partitioned tables have a type of 'p'. For > 10.0 the relkind is not used but for previous versions this needs to be patched.

Please add your comments below so that we can keep all the comments recorded.

cc @hbrunn @NL66278

**Comment by hbrunn** [comment]
@gurneyalex @StefanRijnhart might be interested too

note that from v10, we don't need a mixin any more, but just can add this to `base`. It just occurs to me now that you might complicate things by wanting to add the information about the partitioning to the field definition. Why not having the mixin define a function `_get_partition_info` that returns some data structure encoding the partitions + ranges or whatever else needed? This is simple to inherit, debug, modify. Provide a standard implementation that returns some default partitioning on `id` I guess.

**Comment by daramousk** [comment]
@hbrunn Since we haven't gotten any feedback so far I will start working on this and provide something functional so we can get better overview. Can you please create a 10.0 branch on this project as well? I will implement this on 10.0 and then we can see if there is need for back porting or forward porting.

**Comment by hbrunn** [comment]
just do it for 11 for now, there won't be very big differences

**Comment by StefanRijnhart** [comment]
Does your point 2c not clash with the limitation that is still present in PG11 "While primary keys are supported on partitioned tables, foreign keys referencing partitioned tables are not supported"? I think that stll stands in the way of meaningful usage of partitioned tables in Odoo.

**Comment by hbrunn** [comment]
ah, thanks, that's a very important detail. We'll have to revisit this in 12 then

**Comment by hbrunn** [comment]
closing for now to reopen later

**Comment by nicobustillos** [comment]
This thread has picked my attention. Has there been any followup on PG12? From what I can tell in the following link, that Limitation is no longer there.
[https://www.postgresql.org/docs/12/ddl-partitioning.html](url)

**Comment by theangryangel** [comment]
Certainly interested in this one as well, but I think I’ll be able to throw hardware at the problem for a while. I don’t think I can justify billable time yet (for the project I have this in mind), and I’ll struggle to find out of hours time to implement, but I’d love to help out in any small ways if I can

**Comment by JordiBForgeFlow** [comment]
@hbrunn @daramousk have you actually performed any partitioning in odoo?

**Comment by JordiBForgeFlow** [comment]
Odoo currently does not support partitioned tables https://github.com/odoo/odoo/blob/14.0/odoo/tools/sql.py#L19

**Comment by hbrunn** [comment]
no, this was a failed experiment

**Comment by JordiBForgeFlow** [comment]
@hbrunn see https://github.com/odoo/odoo/pull/66964. One can convert a table to partitioned, manually, and seems to work fine (with limited testing)

**Comment by hbrunn** [comment]
do you have any plans to provide a mixin like the one sketched here? Any measurements already?

**Comment by gdgellatly** [comment]
For reference https://www.2ndquadrant.com/en/blog/partitioning-a-large-table-without-a-long-running-lock/
