### ISSUE TITLE
OCA/server-backend does not deploy on 11.0

### ISSUE THREAD

**Issue by em230418** [OCA/server-backend#173]
Steps to reproduce:
1. Go to https://runboat.odoo-community.org/webui/builds.html?repo=OCA/server-backend
2. Search for 11.0
3. Press "reset"
4. In some time it will show "failed"

Here is the log:
https://runboat.odoo-community.org/api/v1/builds/b77e61fd7-4a7f-4e4f-8f0b-395eae5ecc1c/init-log

**Comment by sbidoul** [comment]
The error is:

```
+ cat test-requirements.txt
MySQLdb
odoo>=11.0a,<11.1dev
pymssql
radicale
sqlalchemy
+ pip install -r test-requirements.txt
Looking in indexes: https://wheelhouse.odoo-community.org/oca-simple-and-pypi
ERROR: Could not find a version that satisfies the requirement MySQLdb
ERROR: No matching distribution found for MySQLdb
```

So the culprit is this MySQLdb for which we need an external_dependencies_override section in the setup.py of base_external_dbsource_mysql.
