### ISSUE TITLE
[16.0] base_external_dbsource_mssql requirements break odoo core compatibily

### ISSUE THREAD

**Issue by flotho** [OCA/server-backend#217]
## Module

base_external_dbsource_mssql 

sqlalchemy in requirements file 

## Describe the bug

the requirement cause incompatibilty issues with greenlet

```
/home/odoo_16/.local/lib/python3.9/site-packages (from -r /home/odoo_16/additionnal_repositories/OCA-server-backend/requirements.txt (line 3)) (2.0.15)\nRequirement already satisfied: typing-extensions>=4.2.0 in /home/odoo_16/.local/lib/python3.9/site-packages (from sqlalchemy->-r /home/odoo_16/additionnal_repositories/OCA-server-backend/requirements.txt (line 3)) (4.5.0)\nCollecting greenlet!=0.4.17 (from sqlalchemy->-r /home/odoo_16/additionnal_repositories/OCA-server-backend/requirements.txt (line 3))\n  **Downloading greenlet-2.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl** (610 kB)\n

```

when greenlet 2.0.2 is installed we have issues like this : https://github.com/gevent/gevent/issues/1685

if I desinstall sqlalchemy and force the installation of the odoo requirements everything works fine

## To Reproduce

install requirement on a v16 with python 3.9

**Expected behavior**

no issue while running Odoo

**Additional context**

rocky linux 9

**Comment by flotho** [comment]
ping @anddago78

**Comment by flotho** [comment]
hum...
looks like it happens for python <= 3.9

**Comment by BT-aleonard** [comment]
Hi @flotho ,
Any news for this bug?

**Comment by flotho** [comment]
yes, I confirm that the requirements has to be adapted regarding the python version

**Comment by flotho** [comment]
this combination of releases works great on v16 :
- sqlalchemy==1.3.24
- greenlet==0.4.17 ; python_version > '3.7' and python_version <= '3.9'
- greenlet==1.1.2 ; python_version  > '3.9' and python_version <= '3.10' # (Jammy)

**Comment by BT-aleonard** [comment]
Thank you very much, did you make a PR to fix this?

**Comment by flotho** [comment]
not at all because I'm not sure how to declare such pattern in manifest files. And if I'm correct requirements are generated by the manifest.
If you lead me on this I can do the PR with pleasure.

**Comment by BT-aleonard** [comment]
You can create a PR to create a requirements file in the repo.

**Comment by flotho** [comment]
> You can create a PR to create a requirements file in the repo.

Hi @BT-aleonard , I disagree with your proposal. Requirements.txt are generated by the dependencies put in the manifest files. And I' m not sure of the pattern .
But anyway I can make a PR to modify manifests ;-)

**Comment by flotho** [comment]
hi @BT-aleonard , finally it was easy, 
feel free to review the PR
Regards
