### ISSUE TITLE
base_user_role: create role from existing user

### ISSUE THREAD

**Issue by gpothier** [OCA/server-backend#218]
I created a module that extends `base_user_role` to add a wizard to create a new role based on an existing user. 

![image](https://github.com/OCA/server-backend/assets/629806/1f70a4fc-da7d-45b0-8fb6-b327e6b9058b)

It basically adds a wizard that permits to create a role that contains the same groups as the selected user.

![image](https://github.com/OCA/server-backend/assets/629806/c83976c8-5337-466c-959c-70dc589dc775)

I'd like to contribute it to OCA. I think it is pretty useful for people who start using `base_user_role` after having already created several users. So:

- Would it be of interest to the community?
- Would it be best to keep it as a separate module, or rather to include the wizard in `base_user_role` module? My personal preference would be to include it in the existing module, as it is very small.

I have a version for Odoo v8 and another for Odoo v16. There are no functional differences between them.

**Comment by legalsylvain** [comment]
Hi. Very Nice feature indeed !
As it is only a transient modèle, i think this feature should go in the main module. 

The contribution should be done on récent version. 8 is too old imo. 

Regards.

**Comment by gpothier** [comment]
Closing as PR #219 was merged
