### ISSUE TITLE
[11.0] ERROR

### ISSUE THREAD

**Issue by cesarsc79** [OCA/server-backend#27]
When you install this module appears this error when you change the company into dashboard (invoicing module)

> Lo siento, no tiene permiso para acceder a este documento. Sólo usuarios con los siguientes permisos están autorizados a hacer esto:
> - Administration/Access Rights
> 
> (Modelo de documento: res.users.role.line)

Only if you put the acces right into user.... it work but, if you dont want give him those acces rights?

**Comment by pedrobaeza** [comment]
@sebalix can you please check this error?

**Comment by sebalix** [comment]
@pedrobaeza I check

**Comment by sebalix** [comment]
@cesarsc79 have you more details to reproduce the problem?
