### ISSUE TITLE
[11.0] ERROR 2

### ISSUE THREAD

**Issue by cesarsc79** [OCA/server-backend#28]
When you try duplicate a record into res.users.role

> Odoo Server Error - Error de validación
¡El nombre del grupo debe ser único en una aplicación!> 

It possible write some like this?

``
@api.multi
def copy(self, default=None):
        default = dict(default or {})
        copied_count = self.search_count(
            [('name', '=like', u"Copy of {}%".format(self.name))])
        if not copied_count:
            new_name = u"Copy of {}".format(self.name)
        else:
            new_name = u"Copy of {} ({})".format(self.name, copied_count)
        default['name'] = new_name
        return super(Course, self).copy(default)

``

**Comment by cesarsc79** [comment]
`@api.multi
    def copy(self, default=None):
        default = dict(default or {})
        copied_count = self.search_count(
            [('name', '=like', u"Copy of {}%".format(self.name))])
        if not copied_count:
            new_name = u"Copy of {}".format(self.name)
        else:
            new_name = u"Copy of {} ({})".format(self.name, copied_count)
        default['name'] = new_name
        return super(Course, self).copy(default)`

**Comment by pedrobaeza** [comment]
@sebalix can you please check this error?

**Comment by sebalix** [comment]
@cesarsc79 I don't know, this is the normal validation constraint about having two users with the same login. Do we want to avoid that?
