### ISSUE TITLE
[12.0] base_user_role direct migration from V11 to V12?

### ISSUE THREAD

**Issue by HaraldPanten** [OCA/server-backend#41]
Hi @pedrobaeza ,

I think this (https://github.com/OCA/server-backend/pull/39) could be directly added to V12 base_user_role module.

Probably these small changes do not require a new PR.

What do you think?

Thanks in advance

**Comment by pedrobaeza** [comment]
A PSC can do the cherry-picking. If not, proceed with the PR. I'm not able to do it right now.

**Comment by HaraldPanten** [comment]
Hi @pedrobaeza and thank you for your prompt reply.

I've been checking https://odoo-community.org/psc-teams/tools-30. Can I ask any of the team members to cherry pick?

THX!

**Comment by HaraldPanten** [comment]
Closing, as I've created a new PR for the changes. See https://github.com/OCA/server-backend/pull/52
