### ISSUE TITLE
Role associated groups created 

### ISSUE THREAD

**Issue by prakashjain** [OCA/server-backend#42]
"base_user_role" version 12 
When creating new role automatic creating group with same name. (Associated group)
In Role Screen, group tab is available, then why extra group(role name group) created while creating role?
If user deleted role, Associated group not deleted is still available in database.
Can we auto delete associated group or completed avoid to create associated group?

**Comment by sebalix** [comment]
@prakashjain the associated group is here for Odoo internals:

- a "role" is a user notion to aggregate groups (it exists only for the UI)
- but the access rights management in Odoo is based on groups (data model access, menus, access rules, views...)

That's why a role is a group under the hood, to be able to map data model access, menus, access rules or views to its group (i.e. display menus or buttons for my "Purchase Manager" role/group).
The group tab shows the sub-groups included by this role/group.

So no, we can not remove this associated group, it is required.

**Comment by prakashjain** [comment]
Thanks for reply, while deleting role can we auto delete associated group? (while testing number of roles
created and deleted. Associated groups still present in database).

**Comment by sebalix** [comment]
It could be a good idea, we need to check that. Feel free to open a PR which add an ondelete='cascade' on the field ;)

**Comment by prakashjain** [comment]
Thank You.
Using the above module i would like to create 4 role (using demo data xml file). Example, 

1. Super Admin Role
2. Admin Role 
3. Sales Role and 
4. Accounting Role.

Able to create Sales and accounting role, But super admin some permission is missing.
using demo data "Super Admin" and "Admin" how to set all groups.  Is any shortcut to create "Super Admin" and "Admin" role and access all group using xml demo data?. Please suggest 
```

    <record id="role_admin" model="res.users.role">
        <field name="name">Super Admin</field>
        <field name="implied_ids" eval="[(4, ref('base.group_erp_manager')),(4, ref('base.group_system')),(4, ref('base.group_no_one'),(4, ref('website.group_multi_website')]"/>
    </record>

     <record id="role_admin" model="res.users.role">
        <field name="name">Admin</field>
        <field name="implied_ids" eval="[(4, ref('base.group_erp_manager')),(4, ref('base.group_system'))]"/>
    </record>

    <record id="role_account_manager_admin" model="res.users.role">
        <field name="name">Sales</field>
        <field name="implied_ids" eval="[(4, ref('sales_team.group_sale_manager')),(4, ref('sale.group_discount_per_so_line'))]"/>
    </record>

     <record id="role_acounting_admin" model="res.users.role">
         <field name="name">Account</field>
         <field name="implied_ids" eval="[(4, ref('account.group_account_manager')),(4, ref('account.group_account_invoice'))]"/>
     </record>
```

**Comment by sebalix** [comment]
@prakashjain Check if `<function>` tag can do the job to perform a search on the targeted data model. I never use it for this use case so I can not help you that much.

**Comment by dreispt** [comment]
> while deleting role can we auto delete associated group? 

+1 for this
