### ISSUE TITLE
[12.0][ERR] base_external_dbsource after migration from v11.0

### ISSUE THREAD

**Issue by Bilbonet** [OCA/server-backend#50]
In v11.0 there is a security rule that referenced the field 'company_id'.
The field 'company_id' doesn't exist in v12 but the rule persist after migration. The module gives this error:

raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'company_id' in leaf "<osv.ExtendedLeaf: ('company_id', '=', False) on base_external_dbsource (ctx: )>"

You have to delete the security rule manually and it's work well.

**Comment by pedrobaeza** [comment]
Can you please add a PR adding the migration script that removes it?

**Comment by Bilbonet** [comment]
I would like :-)
Sorry but I don't have that skill yet. Maybe in a close future.
