### ISSUE TITLE
[12.0] i did the connection and the test was ok but in the readme we need some simple use-cases

### ISSUE THREAD

**Issue by andreampiovesana** [OCA/server-backend#67]
Connection test succeeded:
Everything seems properly set up! 

but i need some example of use
thanks

**Comment by iamstum** [comment]
I am also requiring some documentation of how to implement this in my own custom module, how do you initialize it in the backend? (Using the connection_open_*, connection_close_* and execute_* functions?)
![image](https://user-images.githubusercontent.com/66756980/95793304-fe3e0200-0d30-11eb-954c-72149e861953.png)


I am new to Odoo, this is how I have coded it so far.

 -*- coding: utf-8 -*-
import logging

from odoo import models
from odoo.addons.base_external_dbsource_sqlite.models import base_external_dbsource

_logger = logging.getLogger(__name__)

database = base_external_dbsource.BaseExternalDbsource()
cursor = database.connection_open_sqlite()
_logger.info(cursor.execute_sqlite('select * from student',None,None))


When I run it I get the below error message.

AttributeError: 'NoneType' object has no attribute 'connection_open_sqlite'

**Comment by RicardoCassio** [comment]
Hi, did you find the answer you were looking for? If yes, could you share?
