### ISSUE TITLE
[12.0] base_user_role: Typo role_inernal_notes should be role_internal_notes

### ISSUE THREAD

**Issue by skeller1** [OCA/server-backend#72]
Typing mistake in base_user_role addon in view role.xml

https://github.com/OCA/server-backend/blob/12.0/base_user_role/views/role.xml#L31

**role_inernal_notes** should be **role_internal_notes**

 ```
.....
<page name="role_inernal_notes" string="Internal Notes">
      <field name="comment"/>
</page>
```

**Comment by pedrobaeza** [comment]
Yes, but this doesn't affect anything (as it's an internal name), and changing now in the middle of a stable version can break some inheritances in third modules, so this should be taken into account in a migration.
