### ISSUE TITLE
[RFO] New massive translation terms module

### ISSUE THREAD

**Issue by manuelregidor** [OCA/server-backend#73]
Hi,

We have developed a new module that allows to:

- Export a CVS file that includes the base terms and the translations into multiple languages of multiple fields in the records of a model. It is possible to select the model, the languages, the fields and the records (using a filtering option).
- Import the exported CSV file to include changes on translation or base terms and create new translations and base terms.

  You can check out the README file here: https://github.com/sygel-technology/sy-server-backend/tree/13.0/easy_massive_translation
There is also a post about this topic on our website (in Spanish): https://www.sygel.es/blog/blog-de-sygel-2/post/traducciones-a-diferentes-idiomas-con-una-sola-importacion-7

Do you find it interesting enough for the OCA?

Thank you

**Comment by desdelinux** [comment]
This is a very interesting functionality, which allows to speed up the work of end users. Accelerates the translation process and is applicable in many cases, for example, eccomerce products in multi-language stores

**Comment by alan196** [comment]
I think it's a good module, if you make a PR please ping me to help with the review.

👍

**Comment by manuelregidor** [comment]
@crece365 @alan196 I've opened a PR with the module: https://github.com/OCA/server-backend/pull/82 Could you review it, please?
