### ISSUE TITLE
[13.0] base_user_role : updating implied_ids is not working

### ISSUE THREAD

**Issue by yassinelachgar** [OCA/server-backend#88]
Impacted versions: 13.0

Steps to reproduce:   

- create role via XML and set `implied_ids` to `base.group_erp_manager` for example
- update module so that the data gets created
- go back to the XML and update the implied_ids (remove the old group and replace it with another) `hr.group_hr_user`

Current behavior:   

- updates of the `implied_ids` field from XML are not reflected in the user interface. the field `implied_ids` stays static and never changes even after changing the XML and updating the module.

Expected behavior:   

- updates of the `implied_ids` field from XML should be reflected in the user interface as well as the database.

**Comment by pedrobaeza** [comment]
Which module of this repo?

**Comment by yassinelachgar** [comment]
sorry @pedrobaeza , I've updated the issue title.

**Comment by yassinelachgar** [comment]
> Which module of this repo?

sorry @pedrobaeza , I've updated the issue title.

**Comment by herawais** [comment]
Facing Same issue,
on upgrade module, it does not take effects.
until we create a new database

**Comment by herawais** [comment]
I found a temporary solution 
instead of creating new database to see the change
you can delete the Role and Associated group from frontend
to see the effect

**Comment by yassinelachgar** [comment]
> I found a temporary solution
> instead of creating new database to see the change
> you can delete the Role and Associated group from frontend
> to see the effect

That's not a feasible solution in our case. Deleting the role from front end, will delete the relation between the users and the role. In our case we have hundreds of users for each role, it's a pain to reassign the roles.

**Comment by yassinelachgar** [comment]
@pedrobaeza any idea on who we should tag to see this issue ?

**Comment by pedrobaeza** [comment]
Try with the contributors of the module.

**Comment by yassinelachgar** [comment]
@sebalix Can you check this out please ?

**Comment by ThomasBinsfeld** [comment]
I'm facing the same issue. @sebalix @jcdrubay @novawish Any update about that?
