### ISSUE TITLE
[13.0] base_user_role : Group default application is not set on role creation.

### ISSUE THREAD

**Issue by eferriere** [OCA/server-backend#91]
Impacted versions: 13.0
Module: base_user_role

Steps to reproduce:

* Create a role from the role menu point, filling the name it will be given.

Current behavior:

* When a role is created, no application is set on the user group, which has been created with the role and is linked to it.

Expected behavior:

* On role creation, a user group must be created linked to the role, with the "User roles" category (XML ID: "base_user_role.ir_module_category_role") as application.

**Comment by eferriere** [comment]
This issue is linked to the #92 pull request.

**Comment by StefanRijnhart** [comment]
Closing as the fix is being merged. Thanks for reporting and fixing the bug! If you plan to file a PR, then next time you don't have to open a separate issue.
